### ISSUE TITLE
Caption translation of Eastern Townhall Team Operation

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-captions#11]
The [Eastern Townhall Team Operation](https://c3eth.github.io/catalyst/fund6/eth-proposals/eastern-townhall-team-operation/) video is up and needs captions (subtitles) to be translated. Can you please translate your respective language for us asap?

### Languages 

- [x] [Indonesian](https://gitlocalize.com/repo/6471/id/en/eastern-townhall-operation.md)
- [x] [Japanese](https://gitlocalize.com/repo/6471/ja/en/eastern-townhall-operation.md)
- [x] [Korean](https://gitlocalize.com/repo/6471/ko/en/eastern-townhall-operation.md)
- [x] [Vietnamese](https://gitlocalize.com/repo/6471/vi/en/eastern-townhall-operation.md)

Please check off the translation above when you have completed the task so others know it no longer needs doing. The captions will then be merged into this repository, ready to be uploaded to Youtube. Please note that only the English language versions have captions at the moment.

### Video Subtitles

Once translated the captions need to be uploaded to Youtube via [Youtube Studio](https://studio.youtube.com/video/MzemrlXpqnY/edit)

- [x] Indonesian
- [x] Japanese
- [x] Korean
- [x] Vietnamese

**Comment by YanTirta** [comment]
@wolstaeb , I think I made a mistake. I uploaded the Indonesian subtitles but I seem to have done it over the English subtitles. Can you please teach me how to upload subtitles?

**Comment by wolstaeb** [comment]
All sorted @YanTirta. Corrected the English subtitles and created the Indonesian subtitles on Youtube. You can confirm the results [by watching the video](https://c3eth.github.io/catalyst/fund6/eth-proposals/eastern-townhall-team-operation/).
