### ISSUE TITLE
Caption translation of Onboarding East Asia Today

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-captions#8]
The [Onboarding East Asia Today!](https://c3eth.github.io/catalyst/fund6/eth-proposals/on-board-east-asia-today/) video is up and needs captions (subtitles) to be translated. Can you please translate your respective language for us ASAP.

### Languages

- [x] [Indonesian](https://gitlocalize.com/repo/6471/id/en/onboarding-east-asia-today-captions.md)
- [x] [Japanese](https://gitlocalize.com/repo/6471/ja/en/onboarding-east-asia-today-captions.md)
- [x] [Korean](https://gitlocalize.com/repo/6471/ko/en/onboarding-east-asia-today-captions.md)
- [x] [Vietnamese](https://gitlocalize.com/repo/6471/vi/en/onboarding-east-asia-today-captions.md)

Please check off the translation above when you have completed the task so others know it no longer needs doing. The captions will then be merged into this repository, ready to be uploaded to Youtube. Please note that only the English language versions have captions at the moment.

### Video Subtitles

Once translated the captions need to be uploaded to Youtube via [Youtube Studio](https://studio.youtube.com/video/TR37P2F7QNk/edit)

- [x] Indonesian
- [x] Japanese
- [x] Korean
- [x] Vietnamese

**Comment by andreassosilo** [comment]
Sure @wolstaeb . Will do the translation to Indonesian language this evening. Thanks ☕

**Comment by wolstaeb** [comment]
Comment from @YanTirta which I think is important to note and comment on here.

> Very slight modification in terms of the following; the use of (,), the use of (.), the **editing of double words and most importantly the reoccurring issue**, due to the way the English sentence is broken apart sometimes can cause confusion and unnecessary complexity in translations. Most likely breaking apart a sentence in the middle is not the best practice for translating.

Ideally, a translator would be able to adjust the splitting of words and sorting the timing information. However, a few things to note about the current state of doing captions with GitLocalize which make this a little difficult.

1. GitLocalize does not support caption files (srt, vtt, etc) which means I have symlinked a markdown file to the srt version.
2. As a result GitLocalize reformats the file, such that it becomes an invalid srt.
3. It is also a PITA because it makes it difficult for a translator to resolve the timing of subtitles.

Two ways of fixing this are (neither is a good solution just at the moment).

1. Directly edit the subtitles in Youtube studio. (a few more steps and manual sync'ing back to GH needed)
2. Use another translation tool like POEditor, Lokalise, or Crowdin which do support srt files.

**Comment by YanTirta** [comment]
Very clear now Robert. Thank you for taking your time to describe in
detail. I have looked up all the unfamiliar terms in this context. Would
providing subtitles in srt version directly by me somehow help? Because I
would know what would be the start and end of a sentence, the coma's, the
dot's and so forth.

Seeing your alternative solutions, it seems the current system is currently
the most efficient. Fyi, on a lighter note, it took me a while to find out
what PITA is? When I did, I had a good chuckle :-)

**Comment by wolstaeb** [comment]
@YanTirta There are SRT editors that are better suited to doing the translation of captions. Youtube Studio for instance has one. I just did not use it because I felt that it was an extra step/tool for people to get their heads around. Though imperfect, I figured it would do. 

Rather than discussing Captions translation in an issue for a specific translation task, I will raise it as a separate discussion and we can figure out our next steps for translating captions.

**Comment by YanTirta** [comment]
Duly noted Robert. This "caption translation" thing, I think I see a
potential business model, with a potential large market and believe there's
a current need for it which will grow and I think I already have the KOL's.
And that excites me. The key feature in this potential business model is,
"the crazy speed in translating with an accuracy of 85% to 90% and the wide
variety of languages it could cover". I am more than willing to explore
this by myself *(or with anyone who wants to go down this rabbit hole)* and
as you mentioned, make this a "Translation Department" that is up and
running and making us* (Eastern Townhall)* revenue.

*Looking forward to this separate discussion.*

**Comment by Mietran0407** [comment]
Hi, I am done with the translation for the video caption. Hope it would help for the voting round although it is a little bit late for the Summit.

**Comment by wolstaeb** [comment]
All languages translated.
